k2red_ln_shift/tb added
cisec-su/modmul-hdl pull request #2
Opened 2024-11-27 18:18 UTC by threonyl

Added k2red_ln_shift.v and its sample testbench.

2024-11-29 18:15 UTC, threonyl commented on src/k2red/k2red_ln_shift.v
> +module k2red_ln_shift #(parameter LOG_Q = 32, M = 17, LOG_L = 4, USE_L3 = 1, SPEED_OPT = 1) (
I would like to point out that in the paper we refer to the operand as A (a), not C. But for the sake of uniformity I will make the change according to mont_shift.

2024-12-03 21:07 UTC, threonyl commented
Please see the changes.

- [x] `LOG_Q` -> `LOGQ` (same for all LOGS)
- [x] `M` -> take `LOGQH` as input instead of this. compute M internally, and name it as W (as it is in all others)
- [x] `SPEED_OPT` -> `FF_SHF`
- [x] `Q` -> `qH` (take `qH` only)
- [x] `A` -> `C`
- [x] `l1` -> `L1` (same for others)
- [x] `C2` -> `T`
- [x] Removed unnecessary comments.
- [x] Renamed file.

2024-12-03 21:08 UTC, threonyl commented
> Please see the changes.
> 
>     * [x]  `LOG_Q` -> `LOGQ` (same for all LOGS)
> 
>     * [x]  `M` -> take `LOGQH` as input instead of this. compute M internally, and name it as W (as it is in all others)
> 
>     * [x]  `SPEED_OPT` -> `FF_SHF`
> 
>     * [x]  `Q` -> `qH` (take `qH` only)
> 
>     * [x]  `A` -> `C`
> 
>     * [x]  `l1` -> `L1` (same for others)
> 
>     * [x]  `C2` -> `T`
> 
>     * [x]  Removed unnecessary comments.
> 
>     * [x]  Renamed file.

Also verified and corrected delays for the `L1,2,3` pipeline registers.

2024-12-04 08:41 UTC, toluntosun21 requested changes

2024-12-04 08:41 UTC, toluntosun21 commented on src/k2red/k2red_shift.v
> +module k2red_shift #(parameter LOGQ = 32, LOGQH = LOGQ-17, LOGL = 4, USE_L3 = 1, FF_SHF = 1) (
write LOGQH=15 instead of LOGQ-17.
Format the interface as in the other files (parameters and input/output)

2024-12-04 08:41 UTC, toluntosun21 commented on src/k2red/k2red_shift.v
> +  localparam DELAY  = 4 + (2*FF_SHF)  ; // Latency of the module
we use LAT, instead of DELAY

2024-12-04 17:01 UTC, threonyl commented
- [X] changed `DELAY` to `LAT`
- [X] used `LOGQH` = value, instead of `LOGQH` = `LOGQ`-`W`

2024-12-04 18:53 UTC, merged